export const config = {
  roleID: "1206860573375987762",
  maxDurationTime: 60,
  minDurationTime: 40,
  deleteDuration: 15,
  startHour: 9,
  startMin: 30,
  endHour: 16,
  endMin: 0,
  holidays: [
    {
      name: "New Year’s Day",
      date: "2024-01-01",
      day: "Monday",
    },
    {
      name: "Birthday of Martin Luther King, Jr.",
      date: "2024-01-15",
      day: "Monday",
    },
    {
      name: "Washington’s Birthday",
      date: "2024-02-19",
      day: "Monday",
    },
    {
      name: "Memorial Day",
      date: "2024-05-27",
      day: "Monday",
    },
    {
      name: "Juneteenth National Independence Day",
      date: "2024-06-19",
      day: "Wednesday",
    },
    {
      name: "Independence Day",
      date: "2024-07-04",
      day: "Thursday",
    },
    {
      name: "Labor Day",
      date: "2024-09-02",
      day: "Monday",
    },
    {
      name: "Columbus Day",
      date: "2024-10-14",
      day: "Monday",
    },
    {
      name: "Veterans Day",
      date: "2024-11-11",
      day: "Monday",
    },
    {
      name: "Thanksgiving Day",
      date: "2024-11-28",
      day: "Thursday",
    },
    {
      name: "Christmas Day",
      date: "2024-12-25",
      day: "Wednesday",
    },
  ],
  message: [
    "Align your decisions with your values—start the 4-Step Process now.",
    "Focus on what matters most. Are you practicing the 4-Steps today?",
    "Remember why you started. Take a moment for the 4-Step Sound Psych Process.",
    "Your values are your compass—use the 4-Steps to navigate your day.",
    "Strengthen your focus, reinforce your values—time for the 4-Steps.",
    "Honor your commitments to yourself—do the 4-Steps now.",
    "One step closer to balance—take time for the 4-Step Process.",
    "Have you checked in with your values today? Do the 4-Steps.",
    "A small effort now leads to big gains later—work the 4-Steps.",
    "Let your actions reflect your priorities—engage in the 4-Step Process.",
    "Your future self will thank you—start the 4 Steps today.",
    "Remember, consistency builds mastery—do the 4-Steps.",
    "Stay true to your values—commit to the 4-Step Process.",
    "Your best decisions come from a clear mind—take time for the 4-Steps.",
    "Keep your goals in sight—use the 4-Steps to stay on track.",
    "Success is built on small, consistent actions—do the 4-Steps.",
    "Your values guide your path—let the 4 steps lead the way.",
    "Pause, reflect, and act—time for the 4-Step Process.",
    "Let your actions today reflect the person you want to become—start with the 4 steps.",
    "Balance your life, balance your trading—practice the 4-Steps.",
    "Are your decisions aligning with your values? Take a moment for the 4-Steps.",
    "Prioritize what matters—use the 4-Steps to guide your day.",
    "Small steps, big impact—work through the 4 Steps.",
    "Focus on your values, focus on the 4-Step Process.",
    "The best decisions are value-driven—take time for the 4-Steps.",
    "Remember your why—start with the 4-Step Sound Psych Process.",
    "Consistency breeds success—commit to the 4-Steps.",
    "Align your actions with your aspirations—do the 4 steps.",
    "Stay grounded in your values—practice the 4-Steps.",
    "Your values are the foundation of your decisions—use the 4-Steps.",
    "Strength comes from within—nurture it with the 4-Step Process.",
    "Stay focused, stay committed—start the 4-Steps today.",
    "Your values deserve your attention—take time for the 4-Steps.",
    "The 4-Steps are your pathway to clarity—use them wisely.",
    "Prioritize your well-being—engage in the 4-Step Process.",
    "Let today’s decisions reflect your deepest values—start with the 4-Steps.",
    "Mindful actions lead to meaningful outcomes—practice the 4-Steps.",
    "Your success is rooted in your values—do the 4-Steps.",
    "Ground yourself in what matters most—begin the 4-Step Process.",
    "Align your life with your values—use the 4 Steps as your guide.",
    "Your values are the bedrock of your decisions—commit to the 4-Steps.",
    "Clear your mind, focus your energy—take time for the 4-Steps.",
    "Let your decisions today reflect your values—start the 4-Steps.",
    "Stay true to your path—use the 4 steps to stay aligned.",
    "Your values are your anchor—practice the 4-Step Process.",
    "Consistency is key—commit to the 4-Steps today.",
    "Stay focused on what matters—take time for the 4-Step Sound Psych Process.",
    "Let your values guide your actions—start with the 4 steps.",
    "Reinforce your values with mindful decisions—practice the 4-Steps.",
    "Align your trading with your life’s values—take time for the 4-Steps.",
    "Keep your priorities straight—do the 4-Steps now.",
    "The 4-Steps are your roadmap to balanced decisions—use them.",
    "Stay grounded in your values—take a moment for the 4-Step Process.",
    "Reflect, realign, and act—engage in the 4-Steps.",
    "Your decisions shape your future—make them count with the 4-Steps.",
    "Stay true to your values—commit to the 4-Step Sound Psych Process.",
    "Consistency builds resilience—practice the 4-Steps today.",
    "Your best decisions come from a calm mind—use the 4-Steps.",
    "Keep your values front and center—start the 4-Steps now.",
    "Small actions lead to big changes—commit to the 4-Steps.",
    "Stay aligned with your values—practice the 4-Step Process.",
    "Remember what matters—take time for the 4-Steps.",
    "Your values are your guide—use the 4-Steps to stay on course.",
    "Stay focused, stay aligned—commit to the 4-Steps.",
    "Let your values guide your actions—practice the 4-Step Process.",
    "Your decisions reflect your priorities—make them count with the 4-Steps.",
    "Reinforce your values with every decision—use the 4-Steps.",
    "Stay true to your path—practice the 4 Steps today.",
    "Let your deepest values guide your actions today—start with the 4 steps.",
    "Your values are your compass—use the 4-Steps to navigate your day.",
    "Stay committed to your values—do the 4-Steps now.",
    "Consistency leads to mastery—practice the 4-Steps.",
    "Let your values drive your decisions—take time for the 4-Step Process.",
    "Small steps, big impact—engage in the 4-Steps.",
    "Stay aligned with your values—use the 4 Steps as your guide.",
    "Your decisions today shape your tomorrow—commit to the 4-Steps.",
    "Stay focused on your values—take time for the 4-Step Sound Psych Process.",
    "Your values are your foundation—practice the 4-Steps now.",
    "Stay true to your principles—use the 4-Steps to stay grounded.",
    "Your best decisions come from a clear mind—engage in the 4-Step Process.",
    "Let your actions reflect your priorities—commit to the 4-Steps.",
    "Stay focused on what matters most—practice the 4-Steps today.",
    "Your values deserve your attention—take time for the 4-Step Process.",
    "Small, consistent actions lead to big results—commit to the 4-Steps.",
    "Your values are your anchor—stay grounded with the 4-Steps.",
    "Let your decisions reflect your deepest values today—start the 4-Step Process.",
    "Stay true to your values—commit to the 4-Steps now.",
    "Your actions today shape your future—make them count with the 4-Steps.",
    "Stay aligned with your values—practice the 4-Step Sound Psych Process.",
    "Your best decisions come from a place of clarity—use the 4-Steps.",
    "Let your values guide your path—commit to the 4-Steps.",
    "Stay focused, stay true—practice the 4-Step Process today.",
    "Your values are your compass—use the 4-Steps to stay on course.",
    "Consistency builds success—engage in the 4-Steps now.",
    "Let your decisions reflect your principles—commit to the 4-Steps.",
    "Stay aligned with your values—take time for the 4-Step Process.",
    "Your actions today reflect your priorities—make them count with the 4-Steps.",
    "Let your values guide your decisions—practice the 4-Step Sound Psych Process.",
    "Stay true to your path—commit to the 4 steps now.",
    "Your future self will thank you—take time for the 4-Step Process today.",
    // Add as many messages as you'd like
  ],
};
